# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
import math

Phi = 1.618033988749894848204586834365638117720309179805762862135448#Sloane in the hizzouse!
phi = -0.618033988749894848204586834365638117720309179805762862135448
limit = 4000000
result = []

def binet(n):
	return math.floor((math.pow(Phi,n)/math.sqrt(5)) - (math.pow(phi,n)/math.sqrt(5)))

for i in range(1,40):
	fib = binet(i)
	if (fib%2==0 and fib <= limit):
		result.append(fib)

print math.fsum(result)